# Global log level (everything defaults to INFO)
logging.level.root=INFO


server.port=8082
spring.data.mongodb.uri=mongodb://localhost:27017/orderdb
spring.data.mongodb.database=orderdb
auth.service.url=http://localhost:8080/api/auth

