plugins {
    id 'org.springframework.boot' version '3.5.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'

    // Logging
    implementation 'org.slf4j:slf4j-api:2.0.9'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
